apiVersion: apps/v1beta2
kind: Deployment
metadata:
   name: k8s-spring-sample
spec:
   replicas: 3
   selector:
      matchLabels:
         app: k8s-spring-sample
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   template:
      metadata:
         labels:
            app: k8s-spring-sample
      spec:
         containers: #define the container that will be deployed in the POD
         - name: k8s-spring-sample
           image: caiopereirasousa/k8s-spring-sample #Replace with the name of your image
           ports:
           - containerPort: 8080