apiVersion: apps/v1beta2
kind: Deployment
metadata:
   name: k8s-spring-sample-deploy
spec:
   replicas: 3
   selector:
      matchLabels:
         app: k8s-spring-sample
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   template:
      metadata:
         labels:
            app: k8s-spring-sample
      spec:
         containers:
         - name: k8s-spring-sample
           image: caiopereirasousa/spring-boot-sample #You can replace with the name of your image or use mine
           ports:
           - containerPort: 8080